[package]
name = "pokoebox-bluetooth"
version = "0.1.0"
authors = ["Tim Visée <3a4fb3964f@sinenomine.email>"]
edition = "2018"

[dependencies]
bluez = "0.1.2"
futures = "0.3"
futures-timer = "0.3"
log = "0.4"
tokio-executor = "0.2.0-alpha.1"
tokio-timer = "0.3.0-alpha.5"
