image: "rust:slim"

stages:
  - check
  - build
  - test

variables:
  RUST_VERSION: stable

# Cache rust/cargo/build artifacts
cache:
  key: "$CI_PIPELINE_ID-$RUST_VERSION"
  paths:
    - /usr/local/cargo/registry/
    - /usr/local/rustup/toolchains/
    - /usr/local/rustup/update-hashes/
    - target/

# Install compiler and OpenSSL dependencies
before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends libgtk-3-dev
  - |
    rustup install $RUST_VERSION
    rustup default $RUST_VERSION
  - |
    rustc --version
    cargo --version

# Variable defaults
variables:
  RUST_VERSION: stable
  RUST_TARGET: x86_64-unknown-linux-gnu

# Check on stable, beta and nightly 
.check-base: &check-base
  stage: check
  script:
    - cd ./pokoebox-player
    - cargo check --verbose
    - cargo check --no-default-features --verbose
check-stable:
  <<: *check-base
check-beta:
  <<: *check-base
  variables:
    RUST_VERSION: beta
check-nightly:
  <<: *check-base
  variables:
    RUST_VERSION: nightly
check-old:
  <<: *check-base
  variables:
    RUST_VERSION: "1.39.0"

# Build using Rust stable
build-x86_64-linux-gnu:
  stage: build
  needs:
    - check-stable
  script:
    - cd ./pokoebox-player
    - cargo build --target=$RUST_TARGET --release --verbose
    - mv target/$RUST_TARGET/release/pokoebox-player ./pokoebox-player-$RUST_TARGET
    - strip -g ./pokoebox-player-$RUST_TARGET
  artifacts:
    name: pokoebox-player-x86_64-linux-gnu
    paths:
      - pokoebox-player/pokoebox-player-$RUST_TARGET
    expire_in: 1 month

# Build a static version
build-x86_64-linux-musl:
  stage: build
  needs:
    - check-stable
  variables:
    RUST_TARGET: x86_64-unknown-linux-musl
  script:
    - cd ./pokoebox-player

    # Install the static target
    - rustup target add $RUST_TARGET

    # Install dependencies
    - apt-get install -y musl-tools

    # Statically build
    - cargo build --target=$RUST_TARGET --release --verbose

    # Prepare the release artifact, strip it
    - find . -name pokoebox-player -exec ls -lah {} \;
    - mv target/$RUST_TARGET/release/pokoebox-player ./pokoebox-player-$RUST_TARGET
    - strip -g ./pokoebox-player-$RUST_TARGET
  artifacts:
    name: pokoebox-player-x86_64-linux-musl
    paths:
      - pokoebox-player/pokoebox-player-$RUST_TARGET
    expire_in: 1 month

# Run the unit tests through Cargo
test-cargo:
  stage: test
  needs:
    - check-stable
  dependencies: []
  script:
    - cd ./pokoebox-player
    - cargo test --verbose
