# Configuration for Travis CI
language: rust
sudo: true
rust:
  - nightly

# Install required libraries
before_script:
- sudo apt-get install -y libgtk-3-dev

# Build the player
script:
- cd pokoebox-player
- cargo build
- cargo build --features "rpi"
