[package]
name = "pokoebox-player"
version = "0.0.1"
authors = ["timvisee <timvisee@gmail.com>"]

[dependencies]
gtk = { version = "0.1.2", features = ["v3_14"] }
log = "0.3.7"
cupi = { version = "0.1.0", optional = true }
mio = { version = "0.6.5", optional = true }

[[bin]]
name = "pokoebox-player"
doc = false

[lib]
doc = true

[features]
default = []

# Raspberry Pi features, such as GPIO usage and support for external devices.
# Will compile, but won't run if not running on a Raspberry Pi board.
rpi = ["cupi", "mio"]