[package]
name = "pokoebox-rpi"
version = "0.1.0"
authors = ["Tim Visée <3a4fb3964f@sinenomine.email>"]
edition = "2018"

[dependencies]
bytes = "0.5"
log = "0.4"
pokoebox-common = { version = "*", path = "../pokoebox-common" }
rppal = "0.11"
